# Generated by Django 3.0.3 on 2020-02-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='varname_1',
        ),
    ]
